---
title: "COMPSCIX 415.2 Homework 1"
author: "Michelle Nie"
date: "January 30, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



My Github repository for my assignments can be found at this URL: https://github.com/michelle-nie/compscix-415-2-assignments

```{r load_packages, warning=FALSE, message=FALSE}
library(mdsr)
library(tidyverse)

data("WorldCities")
```


```{r}
glimpse (WorldCities) 
```

Question 1: There are 23,018 observations and 10 variables in the WorldCities data set. Some of the variable names are name, country, and population.

```{r}
WorldCities <- head(WorldCities, 200) 

country_col <- WorldCities$country

unique(country_col)
```


```{r}
# Question 2
region_col <- WorldCities$region
unique(region_col)
```


```{r}
country_col <- select(WorldCities, country)
country_col <- WorldCities %>% select(country)
```


```{r message=FALSE, warning=FALSE}
# Question 3
WorldCities %>% select(country) %>% unique()
```


```{r message=FALSE, warning=FALSE}
# Question 4
WorldCities %>% ggplot(aes(x = population)) + 
  geom_histogram() +
  xlab('City Population')
```


```{r message=FALSE, warning=FALSE}
WorldCities %>% ggplot(aes(x = population)) +
  geom_histogram() +
  xlab('City Population') +
  ylab('Number of Cities') +
  ggtitle('WorldCities Histogram') + 
  theme_bw()
```

